apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy
#  type: LoadBalancer

#eksctl create cluster  --name udacity3 --version 1.18 --with-oidc --without-nodegroup --region us-west-1
